sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20040402
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIOSS_ACCESS_KEY_ID}
    access-key-secret: ${ALIOSS_ACCESS_KEY_SECRET}
    bucket-name: mytest-sky-take-out
  redis:
    host: localhost
    port: 6379
    database: 1
  wechat:
    appid: wx2290dd95eb8ed231
    secret: 8b3cc6592b9fa1f6cb0045da1c5e5ff4
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: http://453ea0fc.r36.cpolar.top/paySuccess
    refundNotifyUrl: http://453ea0fc.r36.cpolar.top/refundSuccess